spring.application.name=naaz
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://localhost:5342/babysteps
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
